### ISSUE TITLE
attempt to index a nil value

### ISSUE THREAD

**Issue by lalitmee** [kabouzeid/nvim-lspinstall#22]
Why I am getting this error? 

- Error
```
E5113: Error while calling lua chunk: ...e/lalitmee/.config/nvim/lua/lk/plugins/nvim_lsp/init.lua:232: attempt to index a nil value
```

I have simply copied and pasted your config from wiki.

This is my config file: https://gist.github.com/lalitmee/0f269db7c4a649094ba01a3c17852bbd

**Comment by kabouzeid** [comment]
Does it work when you remove these 3 lines (https://gist.github.com/lalitmee/0f269db7c4a649094ba01a3c17852bbd#file-lspconfig-lua-L215-L217)?

**Comment by lalitmee** [comment]
Yup, it worked but now I am getting this error for `diagnosticls`
```
Error detected while processing FileType Autocommands for "lua":
E492: Not an editor command: require'lspconfig'["diagnosticls"].manager.try_add()
```
Do I need to configure `diagnostcls` like we have configured `lua` server?

**Comment by kabouzeid** [comment]
Not sure what's happening there without more context.
Yes you need to configure diagnosticls like you need to configure lua for example. I put something together last week (https://github.com/kabouzeid/nvim-lspinstall/issues/4#issuecomment-803579613) :)
Otherwise refer to the diagnosticls documentation.
